<form id="form-stage-results" class="form-horizontal" role="form" action="/index.php/points" enctype="multipart/form-data" method="post" data-url="/index.php/best-team">

    <div class="form-group">
        <label for="stage" class="col-sm-2 control-label">Etapas</label>
        <div class="col-sm-10">
            <select name="stage" id="stage" data-placeholder="Pasirinkite etapą" class="form-control" required="required">
                <?php foreach ($stages as $stage) : ?>
                    <option value="<?= $stage['link'] ?>"><?= $stage['title'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form-group row" style="white-space: nowrap;">

        <div class="col-sm-6">
            <label for="pilot1" class="col-sm-4 control-label">Pilotas Nr. 1</label>
            <div class="col-sm-8">
                <select name="pilot1" id="pilot-1" class="form-control"
                        data-placeholder="Pasirinkite lenktytininką" required="required">
                    <option></option>
                    <?php foreach ($drivers as $team => $driver) : ?>
                        <optgroup label="<?= $team ?>">
                            <?php foreach ($driver as $driver) : ?>
                                <option
                                    value="<?= $driver['driverId'] ?>"><?= sprintf("%d. %s", $driver['driverId'], $driver['title']) ?></option>
                            <?php endforeach; ?>
                        </optgroup>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="col-sm-6">
            <label for="pilot2" class="col-sm-4 control-label">Pilotas Nr. 2</label>
            <div class="col-sm-8">
                <select name="pilot2" id="pilot-2" class="form-control"
                        data-placeholder="Pasirinkite lenktytininką" required="required">
                    <option></option>
                    <?php foreach ($drivers as $team => $driver) : ?>
                        <optgroup label="<?= $team ?>">
                            <?php foreach ($driver as $driver) : ?>
                                <option
                                    value="<?= $driver['driverId'] ?>"><?= sprintf("%d. %s", $driver['driverId'], $driver['title']) ?></option>
                            <?php endforeach; ?>
                        </optgroup>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

    </div>

    <div class="form-group row">

        <div class="col-sm-6">
            <label for="team" class="col-sm-4 control-label">Komanda</label>

            <div class="col-sm-8">
                <select name="team" id="team" data-placeholder="Pasirinkite komandą" class="form-control" required="required">
                    <option></option>
                    <?php foreach ($teams as $team) :?>
                        <option value="<?= $team['title'] ?>"><?= $team['title'] ?></option>
                    <?php endforeach;  ?>
                </select>
            </div>
        </div>

        <div class="col-sm-6">
            <label for="engine" class="col-sm-4 control-label">Variklis</label>

            <div class="col-sm-8">
                <select name="engine" id="engine" data-placeholder="Pasirinkite variklį" class="form-control" required="required">
                    <option></option>
                    <?php foreach ($engines as $engine => $teams) : ?>
                        <option value="<?= $engine ?>"><?= $engine  ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success btn-lg btn-primary">Skaičiuoti</button>
            <button type="button" class="btn btn-default btn-lg">Rasti geriausią etapo komandą</button>
        </div>
    </div>
</form>

<div id="results-panel"></div>
<div id="best-team-panel"></div>