<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>F1 Svajonių Komanda | Skaičiuoklė</title>

    <!-- Bootstrap -->
    <link href="Public/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="Public/css/jumbotron-narrow.css"/>
    <link rel="stylesheet" href="Public/js/plugins/select2/select2.css"/>
    <link rel="stylesheet" href="Public/js/plugins/select2/select2-bootstrap.css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

<div class="container">
    <div class="header">
<!--        <ul class="nav nav-pills pull-right">-->
<!--            <li class="active"><a href="#">Home</a></li>-->
<!--            <li><a href="#">About</a></li>-->
<!--            <li><a href="#">Contact</a></li>-->
<!--        </ul>-->
        <h3 class="text-muted">F1 Svajonių Komandos skaičiuoklė</h3>
    </div>

    <?=$content?>

    <div class="footer">
        <p>&copy; Jokūbas Ramanauskas 2014</p>
    </div>

</div>
<!-- /container -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="Public/js/bootstrap.min.js"></script>
<script src="Public/js/plugins/select2/select2.min.js"></script>

<script src="Public/js/general.js"></script>

</body>
</html>