<?php foreach ($results as $eventType => $eventResults) :?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?=$eventType?></h3>
        </div>
        <div class="panel-body">
            <?php foreach ($eventResults as $type => $value) :?>
                <p>
                    <strong><?=$type?></strong>: <?=$value?>
                </p>
            <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>